[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gg", email = "georgevanderveen@yahoo.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "channels>=4.3.2",
    "daphne>=4.2.3",
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.18.1",
    "djangorestframework-simplejwt>=5.5.1",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
